KeySuites/Models/Company.cs
namespace Vidly.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Company
    {
        
        [Required]
        [StringLength(500)]
        public string CompanyEmail { get; set; }

        [StringLength(500)]
        public string CompanyName { get; set; }

        
        [StringLength(500)]
        public string Website { get; set; }

        [StringLength(500)]
        public string CompanyContact { get; set; }

        public Int64 CompanyId { get; set; }
        [StringLength(500)]
        public string Address { get; set; }

        public string Address2 { get; set; }

        public string PreferedArea { get; set; }

        public string City { get; set; }

        public string State { get; set; }
        [Column(TypeName = "numeric")]
        public decimal? Zip { get; set; }
        public bool IsActive { get; set; }

        
    }
}

KeySuites/Models/Contact.cs
namespace Vidly.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Contact
    {
       

        public Int64 Id { get; set; }

        [Required]
        [StringLength(500)]
        public string Email { get; set; }

        [StringLength(500)]
        public string Company { get; set; }

        [StringLength(500)]
        public string LastName { get; set; }

        [StringLength(500)]
        public string FirstName { get; set; }

        [StringLength(500)]
        public string Phone { get; set; }

        public Int64 CompanyId { get; set; }
        [StringLength(500)]
        public string Address { get; set; }

        public string Address2 { get; set; }


        public string City { get; set; }

        public string State { get; set; }
        [Column(TypeName = "numeric")]
        public Int64? Zip { get; set; }

        public bool IsActive { get; set; }

        public DateTime DOB { get; set; }


    }
}

KeySuites/Models/Lead.cs
namespace Vidly.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Lead
    {
        [Key]
        [Column(TypeName = "numeric")]
        public Int64 LeadsId { get; set; }

        public string ContactType { get; set; }

        [StringLength(500)]
        public string LeadsName { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? ContactInfoId { get; set; }

        [StringLength(500)]

        public string ContactNumber  { get; set; }
        
        [StringLength(500)]
        public string ContactEmail  { get; set; }

        [StringLength(500)]
        public string OcupantName  { get; set; }
        public string NoOfAdults { get; set; }

        public string NoOfChildren { get; set; }

        public string NoOfPets { get; set; }

        [StringLength(50)]
        public string Breed { get; set; }

        public decimal? Weight { get; set; }

        [StringLength(500)]
        public string PreferedArea { get; set; }

        [StringLength(500)]
        public string Address { get; set; }

        [StringLength(500)]
        public string City { get; set; }

        [StringLength(500)]
        public string State { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? Zip { get; set; }

        [StringLength(500)]
        public string Address2 { get; set; }

        [StringLength(500)]
        public string OccupantCity { get; set; }

        [StringLength(500)]
        public string OccupantState { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? OccupantZip { get; set; }

        public string NoOfBedRooms { get; set; }

        [Column(TypeName = "date")]
        public DateTime? MoveInDate { get; set; }

        [StringLength(500)]
        public string LeaseTerm { get; set; }

        [StringLength(500)]
        public string FloorPreference { get; set; }

        [StringLength(500)]
        public string ReferelSource { get; set; }

        [StringLength(500)]
        public string Notes { get; set; }

        [StringLength(500)]
        public string CompanyLogo { get; set; }

        [StringLength(500)]
        public string CompanyContactNumber { get; set; }


        [StringLength(500)]
        public string ContactNumberCompany { get; set; }


        [StringLength(500)]
        public string ContactName { get; set; }

        [StringLength(500)]
        public string PreferedAddress { get; set; }


        [StringLength(500)]
        public string Elevator { get; set; }
        public bool IsActive { get; set; }

        public ReferalSource referalSource { get; set; }

    }
}

KeySuites/Models/PropContact.cs
namespace Vidly.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class PropContact
    {
       

        public Int64 PropContactId { get; set; }
        public Int64 PropertyId { get; set; }
        [Required]
        [StringLength(500)]
        public string PropContactEmail { get; set; }

        
        [StringLength(500)]
        public string PropContactLastName { get; set; }

        [StringLength(500)]
        public string PropContactFirstName { get; set; }

        [StringLength(500)]
        public string PropContactNumber { get; set; }

       
    }
}

KeySuites/Models/Reservation.cs
namespace Vidly.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Reservation
    {
        [Key]
        [Column(TypeName = "numeric")]
        public Int64 RId { get; set; }

        [Column(TypeName = "numeric")]
        public Int64? QouteId { get; set; }

        [Column(TypeName = "numeric")]
        public Int64? PropertyId { get; set; }

        public DateTime? LeaseStartDate { get; set; }

        public DateTime? LeaseEndDate { get; set; }

        public DateTime? CheckInTime { get; set; }

        [StringLength(1000)]
        public string ArrivalInstructions { get; set; }

        public DateTime? CheckOutTime { get; set; }

        [StringLength(1000)]
        public string DepartureInstructions { get; set; }

        public decimal? TotalOneTime { get; set; }

        public decimal? TotalMonthly { get; set; }

        public Property property { get; set; }

        public Quote quote { get; set; }
        public bool IsActive
        { get; set; }

        public string CheckinKeyArrangements { get; set; }

        public string EntryGateCode { get; set; }

        public string MailboxNumber { get; set; }
        public string MailboxLocation { get; set; }
        public string TrashDisposal { get; set; }
        public string WifiNetworkName { get; set; }

        public string WifiPassword { get; set; }
        public string Housekeeping { get; set; }
        public string ParkingNumberofspaces { get; set; }
        public string ParkingAssignedSpace { get; set; }
        public string ParkingBusinessCenterHours { get; set; }
        public string ParkingFitnessCenterHours { get; set; }

        public string ParkingPoolHours { get; set; }

        public string CustomerServiceNumber { get; set; }

        public string Emergencynumber { get; set; }

        public string GuestName { get; set; }
        public string Status { get; set; }
    }
}

KeySuites/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Microsoft.Data.SqlClient;
using System.Web;
using System.Web.Mvc;
//using System.Data.Entity;
using Vidly.Models;
using ElasticsearchCRUD.Model.GeoModel;
using System.Text.RegularExpressions;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;

using System.Text;
using System.Runtime.InteropServices;
//using GroupDocs.Conversion.Options.Convert;

//using DocuSign.eSign;
//using DocuSign.eSign.Api;
//using DocuSign.eSign.Client;
//using DocuSign.eSign.Model;

using DocumentFormat.OpenXml;
//using DocumentFormat.OpenXml.Packaging;
//using DocumentFormat.OpenXml.Wordprocessing;

using System.IO;
using A = DocumentFormat.OpenXml.Drawing;
using DW = DocumentFormat.OpenXml.Drawing.Wordprocessing;
using PIC = DocumentFormat.OpenXml.Drawing.Pictures;
namespace Vidly.Controllers
{
    public class SetupController : Controller
    {

        #region Class Global Members
        public decimal graphAssetID = 0;

        public string connect = Injector.SConnection;
        #endregion

        #region Class Action Methods
        [HttpPost]
        public ActionResult Index(string latitude = "")
        {
            ViewBag["id"] = 0;
            return View();
        }

        /// <summary>
        /// ///////Referel
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        /// 

        public ActionResult MapTest()
        {
            return View();
        }
        public string OpenModelPopup()
        {
            //can send some data also.  
            return "<h1>This is Modal Popup Window</h1>";
        }

        public ActionResult ReferelSources(decimal id = 0)
        {

            //string connect = System.Configuration.ConfigurationManager.ConnectionStrings["KeySuitesCon"].ConnectionString;
            //SqlConnection con = new SqlConnection("Server =.\\MSSQLSERVER19; Initial Catalog = simplicity; Persist Security Info = False; User ID = sa; Password = sa; MultipleActiveResultSets = False; Encrypt = false; TrustServerCertificate = true; Connection Timeout = 200");
            if (Session["LoginUserRole"] != null)
            {

            }
            else
            {
                return RedirectToAction("Login", "Account");
            }

            if (Session["SuccessMessage"] != null)
            {
                if (Session["SuccessMessage"].ToString() != "")
                {
                    ViewData["SuccessMessage"] = Session["SuccessMessage"].ToString();
                    Session["SuccessMessage"] = null;
                }
                else
                {
                    Session["SuccessMessage"] = null;
                }

            }
            else
            {
                ViewData["SuccessMessage"] = "";
            }

            //Add View
            if (ViewData["error"] == null || ViewData["error"].ToString() == "")
            {
                if (Session["error"] != null)
                {

                    ViewData["error"] = Session["error"].ToString();
                }
                else
                {

                    ViewData["error"] = "";
                }
            }
            /////List<ReferalSource> referalSources = new List<ReferalSource>();
            /////return View(referalSources);
            return View(BindDataReferalAll(id));
        }

        public ActionResult AddReferel(Int64 Id = 0)
        {
            if (Session["LoginUserRole"] != null)
            {

            }
            else
            {
                return RedirectToAction("Login", "Account");
            }

            //string connect = System.Configuration.ConfigurationManager.ConnectionStrings["KeySuitesCon"].ConnectionString;
            //SqlConnection con = new SqlConnection("Server =.\\MSSQLSERVER19; Initial Catalog = simplicity; Persist Security Info = False; User ID = sa; Password = sa; MultipleActiveResultSets = False; Encrypt = false; TrustServerCertificate = true; Connection Timeout = 200");
            SqlConnection con = new SqlConnection(connect);
            SqlCommand cmd = new SqlCommand("ReferalSourcesSelect", con);

            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@ReferalSourceId", Id);
            SqlDataReader Dr;
            con.Open();
            Dr = cmd.ExecuteReader();
            DataTable dt = new DataTable("Vw");
            dt.Load(Dr);

            con.Close();

            ReferalSource ReferalSource_Single = new ReferalSource();
            ReferalSource ReferalSource_Detail = new ReferalSource();
            JsonResult jR = new JsonResult();
            List<ReferalSource> ReferalSource_List = new List<ReferalSource>();
            //var items = dbContext.VwAppUserAssets.AsNoTracking().AsQueryable<Models.VwAppUserAsset>();
            if (dt.Rows.Count > 0)
            {


                ReferalSource_Single.Address = dt.Rows[0]["Address"].ToString();

                ReferalSource_Single.ReferalSourceId = Int64.Parse(dt.Rows[0]["ReferalSourceId"].ToString());

                ReferalSource_Single.CompanyName = dt.Rows[0]["CompanyName"].ToString();
                ReferalSource_Single.ReferalType = dt.Rows[0]["ReferalType"].ToString();
                ReferalSource_Single.Number = decimal.Parse(dt.Rows[0]["Number"].ToString());
                ReferalSource_Single.CostPerDay = decimal.Parse(dt.Rows[0]["CostPerDay"].ToString());

                ReferalSource_Single.Address = dt.Rows[0]["Address"].ToString();
                ReferalSource_Single.Address2 = dt.Rows[0]["Address2"].ToString();
                ReferalSource_Single.City = dt.Rows[0]["City"].ToString();
                ReferalSource_Single.State = dt.Rows[0]["State"].ToString();
                //ReferalSource_Single.Zip = Int64.Parse(dt.Rows[0]["zip"].ToString());

                if (dt.Rows[0]["Zip"] == null || dt.Rows[0]["Zip"].ToString() == "" || Int64.Parse(dt.Rows[0]["Zip"].ToString()) == 0)
                {
                    ReferalSource_Single.Zip = null;
                }
                else
                {
                    ReferalSource_Single.Zip = Int64.Parse(dt.Rows[0]["Zip"].ToString());
                }

                ViewBag.ReferalType = DropDownListReferelType(dt.Rows[0]["ReferalType"].ToString());
                ViewBag.States = BindDataStatesAll(0);
            }
            else
            {
                ReferalSource_Single = new ReferalSource() { Zip = 75881, State = "TX", City = "Houston", Address2 = "", CostPerDay = 0, ReferalSourceId = 0, ReferalType = "", CompanyName = "", Address = "", Number = 0 };
                ViewBag.ReferalType = DropDownListReferelType("");
                ViewBag.States = BindDataStatesAll(0);
            }



            return View(ReferalSource_Single);
        }

        [HttpPost]
        public ActionResult AddReferel(FormCollection model)
        {
            Session["Message"] = "";
            Session["SuccessMessage"] = "";
            Session["Message"] = "";
            Session["SuccessMessage"] = "";
            Session["error"] = null;
            ReferalSource ReferalSource_Save = new ReferalSource();

            ReferalSource_Save.ReferalSourceId = Int64.Parse(model["ReferalSourceId"]);

            ReferalSource_Save.ReferalType = model["ReferalType"].ToString();


            ReferalSource_Save.Address = model["Address"];
            if (ReferalSource_Save.Address == null)
                ReferalSource_Save.Address = "";

            ReferalSource_Save.CompanyName = model["CompanyName"].ToString();
            if (ReferalSource_Save.CompanyName == null)
                ReferalSource_Save.CompanyName = "";

            ReferalSource_Save.Number = decimal.Parse(model["Number"].ToString());
            if (ReferalSource_Save.Number == null)
                ReferalSource_Save.Number = 0;

            ReferalSource_Save.CostPerDay = decimal.Parse(model["CostPerDay"].ToString());


            ReferalSource_Save.Address = model["Address"].ToString();
            ReferalSource_Save.Address2 = model["Address2"].ToString();
            ReferalSource_Save.City = model["City"].ToString();
            ReferalSource_Save.State = model["State"].ToString();
            //ReferalSource_Save.Zip = Int64.Parse(model["zip"].ToString());
            if (model["Zip"] == null || model["Zip"].ToString() == "")
            {
                ReferalSource_Save.Zip = 0;
            }
            else
            {
                ReferalSource_Save.Zip = Int64.Parse(model["Zip"].ToString());
            }

            //if (Session["LoginUserRole"] != null)
            //{
            //    //vwAppUserAsset_Save.last_update_user_id = Session["LoginUserEmail"].ToString();
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Account");
            //}


            SqlConnection con = new SqlConnection(connect);
            //SqlCommand cmd = new SqlCommand("select manufacturer_id, asset_id, asset_name,  deviceSN, folder_Id, external_id, active_ind, asset_description, latitude, longitude, street_address_1, street_address_2, asset_created_by, logical_termination_dt from dbo.asset where activated_by = 'admin@simplicityintegration.com'", con);

            //con.Open();
            using (SqlCommand cmd = new SqlCommand())
            {
                cmd.Connection = con;
                cmd.CommandType = CommandType.Text;
                if (ReferalSource_Save.ReferalSourceId == 0)
                {


                    if (!DuplicateReferel(ReferalSource_Save.CompanyName))
                    {
                        cmd.CommandText = "ReferalSourcesInsert";
                        cmd.CommandType = CommandType.StoredProcedure;

KeySuites/Views/Setup/AddReferel.cshtml
@model Vidly.Models.ReferalSource
@{ ViewBag.Title = "New";
    Layout = null; }
@{
    ViewData["Title"] = "Add Referel Source";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>


<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">Add Referral</h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/Setup/ReferelSources">Referral</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Add Referral </li>
                </ol>
            </nav>
        </div>
        @if (ViewData["Message"] != "" && ViewData["Message"] != null)
        {
            <div class="row" style="display:block">
                <div class="col-sm-2">

                </div>
                <div class="alert alert-warning" style="background-color:lightcoral" role="alert">
                    @Html.Label("Error: " + ViewData["Message"].ToString(), new { @style = "color:black" })
                </div>
            </div>

        }
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Add Referral</h4>

                            @using (Html.BeginForm("AddReferel", "Setup"))
                            {

                                <div class="row">
                                    <div class="col-md-2 border-dark-light">
                                        <div class="form-group label-floating ">
                                            @Html.Label("Referral Type", new { @class = "control-label", @style = "font-size:12px;color:black" })
                                            @Html.DropDownList("ReferalType", ViewBag.ReferalType as IEnumerable<SelectListItem>, new { @class = "  btn btn-success", @style = "font-size:12px;color:black" })
                                            @Html.ValidationMessageFor(m => m.ReferalType)
                                        </div>
                                    </div>


                                </div>

                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group label-floating">
                                            @Html.Label("Referral Name", new { @class = "control-label", @style = "font-size:12px;color:black" })
                                            @Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control border-dark", @type = "varchar", @style = "border-radius:10px;background-color:oldlace", @required = "required" })
                                            @Html.ValidationMessageFor(m => m.CompanyName)
                                        </div>
                                    </div>

                                </div>
                                <div class="row">

                                    <div class="col-md-3">
                                        <div class="form-group label-floating">
                                            @Html.Label("Address 1", new { @class = "control-label", @style = "font-size:12px;color:black" })
                                            @Html.TextBoxFor(m => m.Address, new { @class = "form-control border-dark", @type = "varchar", @style = "border-radius:10px" })
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group label-floating">
                                            @Html.Label("Address 2", new { @class = "control-label", @style = "font-size:12px;color:black" })
                                            @Html.TextBoxFor(m => m.Address2, new { @class = "form-control border-dark", @type = "varchar", @style = "border-radius:10px" })
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group label-floating">
                                            @Html.Label("City", new { @class = "control-label", @style = "font-size:12px;color:black" })
                                            @Html.TextBoxFor(m => m.City, new { @class = "form-control border-dark", @type = "varchar", @style = "border-radius:10px" })
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group label-floating">
                                            @Html.Label("State", new { @class = "control-label", @style = "font-size:12px;color:black" })
                                            @Html.TextBoxFor(m => m.State, new { @class = "form-control border-dark", @type = "varchar", @style = "border-radius:10px", @readonly = true })
                                            <a class="btnLink" data-toggle="modal" data-target="#exampleModal" title="Select State"><i class=" bg-info mdi mdi-search-web" style="font-size:large"></i></a>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group label-floating">
                                            @Html.Label("Zip", new { @class = "control-label", @style = "font-size:12px;color:black" })
                                            @Html.TextBoxFor(m => m.Zip, new { @class = "form-control border-dark", @type = "number", @value = "75881", @onkeypress = "return allowNumberOnly(event)", @style = "border-radius:10px" })
                                            <div id="savealert" class="alert alert-warning" style="background-color:lightcoral; display:none" role="alert">
                                                @Html.Label("Zip code must be valid", new { @style = "color:black" })
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group label-floating">
                                            @Html.Label("Dollar/Percentage", new { @class = "control-label", @style = "font-size:12px;color:black" })
                                            @Html.TextBoxFor(m => m.Number, new { @class = "form-control border-dark", @type = "number", @step = ".01", @style = "border-radius:10px;background-color:oldlace", @required = "required" })
                                            @Html.ValidationMessageFor(m => m.Number)
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group label-floating">
                                            @Html.Label("Cost Per Day", new { @class = "control-label", @style = "font-size:12px;color:black" })
                                            @Html.TextBoxFor(m => m.CostPerDay, new { @class = "form-control border-dark", @type = "number", @step = ".01", @value = "0", @style = "border-radius:10px;background-color:oldlace", @required = "required" })
                                            @Html.ValidationMessageFor(m => m.CostPerDay)
                                        </div>
                                    </div>
                                </div>


                                <div class="row" style="display:none">
                                    <div class="font-weight-lighter">
                                        <code>In Case of %</code><hr /><p>Total Cost = Total stay * Cost Per Day  AND Final Amount = % Percentage + Total cost</p>
                                        <hr /><code>In Case of $</code><hr /><p>Final Amount = Total Stay * Cost Per Day</p>
                                    </div>

                                </div>
                                <div class="row">

                                </div>
                                <div class="row">
                                    <div id="exampleModal" class="modal" tabindex="-1" role="dialog">
                                        <div class="col-lg-12 grid-margin stretch-card">
                                            <div class="card">

                                                <div class="card-body">
                                                    <h4 class="card-title">States Lookup</h4>
                                                    @Html.Partial("_States", (IEnumerable<Vidly.Models.States>)ViewBag.States)
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">

                                </div>
                                <div class="row">

                                </div>
                                <div class="row">
                                    @Html.HiddenFor(m => m.ReferalSourceId)
                                    <div class="col-md-12">
                                        @Html.AntiForgeryToken()
                                        <button type="submit" class="btn btn-primary btn-rounded btn-fw" onclick="return zipcheck()">

                                            Save
                                        </button>
                                        <a href="/Setup/ReferelSources" class="btn btn-light btn-rounded btn-fw">
                                            Cancel
                                        </a>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @*@section scripts {
            <link rel="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"
                  type="text/css" />
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"
                    type="text/javascript"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
            <script>
                $(function () {
                    $(".selectpicker").selectpicker();
                });
            </script>
        }*@


    <script type="text/javascript">

        $(function () {
            $("#submit").click(function () {
                var vall1 = $('#Zip').val()
                //alert(vall1.length);
                //alert(monthlyKSProfit);
                if (vall1.length > 0 && vall1.length < 5) {
                    //alert(vall1.length);
                    document.getElementById('savealert').style.display = 'block'
                    return false;
                }
                else {
                    document.getElementById('savealert').style.display = 'none'

                }
            });
        });

        function zipcheck () {
                var vall1 = $('#Zip').val()
                //alert(vall1.length);
                //alert(monthlyKSProfit);
            if (vall1.length > 0 && vall1.length < 5) {
                    //alert(vall1.length);
                    document.getElementById('savealert').style.display = 'block'
                    
                    return false;
                }
                else {
                    document.getElementById('savealert').style.display = 'none'

                }
            }

    </script>


    <script>
        function buttonclickStates(param, param1) {
            //you can access that value using the variable param.
            //Or you can give any name of your choice.
            $('#State').val(param); //to put that value in your textbox.

            $('#exampleModal').modal('toggle'); //you can also use 'hide' instead of 'toggle' to close your modal.
        }
    </script>

    <script>
        function allowNumberOnly(e) {
            var vall1 = $('#Zip').val()
            var ascii = (e.which) ? e.which : e.keyCode
            if (ascii > 31 && (ascii < 48 || ascii > 57)) {
                return false;
            }
            
            else {
                var vall = $('#Zip').val()
                if (vall.length > 4) {
                    return false;
                }
                else {
                    return true;
                }
            }
        }
    </script>